// ORRGANIZATION REPRESENTOR 
export const ORGANIZATION_REPRESENTOR_VERIFY = "ORGANIZATION_REPRESENTOR_VERIFY"
export const ORGANIZATION_REPRESENTOR_SUCCESS = "ORGANIZATION_REPRESENTOR_SUCCESS"
export const ORGANIZATION_REPRESENTOR_FAIL = "ORGANIZATION_REPRESENTOR_FAIL"
export const ORGANIZATION_REPRESENTOR_REQUEST = "ORGANIZATION_REPRESENTOR_REQUEST"

// PERSONAL REPRESENTOR 
export const PERSONAL_REPRESENTOR_VERIFY = "PERSONAL_REPRESENTOR_VERIFY"
export const PERSONAL_REPRESENTOR_SUCCESS = "PERSONAL_REPRESENTOR_SUCCESS"
export const PERSONAL_REPRESENTOR_FAIL = "PERSONAL_REPRESENTOR_FAIL"
export const PERSONAL_REPRESENTOR_REQUEST = "PERSONAL_REPRESENTOR_REQUEST"