export const SHORTCUT_ADD_REQUEST = 'SHORTCUT_ADD_REQUEST';
export const SHORTCUT_ADD_SUCCESS = 'SHORTCUT_ADD_SUCCESS';
export const SHORTCUT_ADD_FAIL = 'SHORTCUT_ADD_FAIL';

export const SHORTCUT_LIST_REQUEST = 'SHORTCUT_LIST_REQUEST';
export const SHORTCUT_LIST_SUCCESS = 'SHORTCUT_LIST_SUCCESS';
export const SHORTCUT_LIST_FAIL = 'SHORTCUT_LIST_FAIL';

export const SHORTCUT_DETAILS_REQUEST = 'SHORTCUT_DETAILS_REQUEST';
export const SHORTCUT_DETAILS_SUCCESS = 'SHORTCUT_DETAILS_SUCCESS';
export const SHORTCUT_DETAILS_FAIL = 'SHORTCUT_DETAILS_FAIL';

export const SHORTCUT_UPDATE_REQUEST = 'SHORTCUT_UPDATE_REQUEST';
export const SHORTCUT_UPDATE_SUCCESS = 'SHORTCUT_UPDATE_SUCCESS';
export const SHORTCUT_UPDATE_FAIL = 'SHORTCUT_UPDATE_FAIL';

export const SHORTCUT_DELETE_REQUEST = 'SHORTCUT_DELETE_REQUEST';
export const SHORTCUT_DELETE_SUCCESS = 'SHORTCUT_DELETE_SUCCESS';
export const SHORTCUT_DELETE_FAIL = 'SHORTCUT_DELETE_FAIL';